language: elixir
sudo: false
notifications:
  email: false

elixir:
  - 1.8
  - 1.7

otp_release:
  - 21.1
  - 20.3
  - 19.3
  - 18.3

matrix:
  exclude:
    - elixir: 1.8
      otp_release: 19.3
    - elixir: 1.8
      otp_release: 18.3

script:
  - make testing

before_cache:
  - rf -rf _build/$MIX_HOME/lib

cache:
  directories:
    - _build/$MIX_HOME

after_script:
  - make docs
after_success:
  - bash <(curl -s https://codecov.io/bash)
